name: Package Release APK

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'
          cache-dependency-path: |
            gradlew
            settings.gradle.kts
            build.gradle.kts
            app/build.gradle.kts
      - name: Build Release APK
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assembleRelease
      - name: Commit and push to homebrew repo
        run: mv app/build/outputs/apk/release/app-release-unsigned.apk ./gol-screensaver.apk
      - name: Upload Release APK
        uses: softprops/action-gh-release@v2
        with:
          files: gol-screensaver.apk