name: Package Release APK

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'
          cache-dependency-path: |
            gradlew
            settings.gradle.kts
            build.gradle.kts
            app/build.gradle.kts
      - name: Build Release APK
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assembleRelease
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "36.0.0"
      - name: List APKs
        run: ls -l app/build/outputs/apk/release/
      - name: Upload Release APK
        uses: softprops/action-gh-release@v2
        with:
          files: ${{steps.sign_app.outputs.signedReleaseFile}}
